services:
  - docker
before_install:
  - docker version

script:
- echo "run docker build"
- docker build -t samuraitruong/netcore-nodejs-chromium .
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
