services:
  - docker
before_install:
  - docker version

script:
- bundle exec rake test
- docker build -t netcore-nodejs-chromenium -f Dockerfile
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
