services:
  - docker
before_install:
  - docker version

script:
- echo "run docker build"
- docker build -t samuraitruong/netcore-nodejs-chromium:latest .
- docker build -t samuraitruong/netcore-nodejs-chromium:2.2 -f Dockerfile_2.2 .
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
